server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teste
    username: root
    password: 071273Fr@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect


jwtSecret: "c5e1a9a5003631cda0be62de61815528e3de015d"
jwtExpiration: 3600000